In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3,4,5,6], [5,6,7,7,8,9]])
print(b)

[[1 2 3 4 5 6]
 [5 6 7 7 8 9]]


In [5]:
a.ndim


1

In [6]:
b.ndim

2

In [7]:
b.shape

(2, 6)

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.size

3

In [12]:
a.nbytes

12

In [15]:
c = np.array([[1,2,3,4,5,6], [8,9,2,4,5,6]])
print(c)

[[1 2 3 4 5 6]
 [8 9 2 4 5 6]]


In [17]:
c[1,5]

6

In [19]:
c[0, :]

array([1, 2, 3, 4, 5, 6])

In [20]:
c[0, 1:6:2]

array([2, 4, 6])

In [21]:
c[1,5] = 20
print(c)

[[ 1  2  3  4  5  6]
 [ 8  9  2  4  5 20]]


In [23]:
d = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
d[0, 1, 1]

4

In [32]:
np.zeros(((3,3,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [34]:
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [35]:
np.random.rand(4,2)

array([[0.18716536, 0.58564432],
       [0.07776727, 0.96596332],
       [0.9858822 , 0.52015681],
       [0.35770712, 0.93110654]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
arr = np.array([[1,7,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 7 3]
 [1 7 3]
 [1 7 3]]


In [53]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
a = np.array([1,2,3,4])
a + 2

array([3, 4, 5, 6])

In [49]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])